In [1]:
def compute_dev(n,d):
    try:
        result= n/d
    except Exception as out:
        print("There is a failure in the program" + " Error: " + str(out))
    else:
        print("The divison program is completed" + " output is: " + str(result))

In [2]:
compute_dev(5,3)

The divison program is completed output is: 1.6666666666666667


In [4]:
compute_dev(5,0)

There is a failure in the program Error: division by zero


In [5]:
subject = ["Americans","Indians"] 
verb = ["Play", "watch"]
objects = ["Baseball","cricket"]

for sub in subject:
    for ver in verb:
        for obj in objects:
            out_statement=str(sub) + " " + ver + " " + obj
            print(out_statement)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [11]:
import numpy as np
   
def gen_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    return op_matx

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = gen_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_matrix(inputvector,no_col_opmat,True)

print("Input Array : \n ",inputvector)
print("Outpt matrix in decreasing order :\n",op_matx_dec_order)
print("Output matrix in increasing order :\n",op_matx_inc_order)

Input Array : 
  [1 2 3 4 5]
Outpt matrix in decreasing order :
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
Output matrix in increasing order :
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
